/**
 * @author  Peter Jakobs http://github.com/pljakobs
 */

#include "include/Esp32HardwarePwm.h"
// HW_PWM_DEBUG controls logging for this component only (0=off, 1=errors, 2=+info, 3=full).
// Set via -DHW_PWM_DEBUG=<level> in your Makefile or component.mk (default: 0).
#ifndef HW_PWM_DEBUG
#define HW_PWM_DEBUG 0
#endif
#undef ENABLE_DEBUG
#define ENABLE_DEBUG HW_PWM_DEBUG
#include <debug_progmem.h>
#include <Platform/System.h>
#include <driver/periph_ctrl.h>
#include <esp_err.h>
#include <esp_random.h>
#include <esp_timer.h>
#include <algorithm>
#include <cassert>

/****
 * Sming Framework Project - Open Source framework for high efficiency native ESP8266 development.
 * Created 2015 by Skurydin Alexey
 * http://github.com/SmingHub/Sming
 * All files of the Sming Core are provided under the LGPL v3 license.
 *
 * Esp32HardwarePWM.cpp
 *
 * Esp32 version:   https://github.com/pljakobs
 *
 * This Esp32HardwarePWM library enables Sming framework users to use the ESP32 LEDC PWM API
 * 
 * The ESP32 PWM Hardware is much more powerful than the ESP8266, allowing wider PWM timers (up to 20 bit)
 * as well as much higher PWM frequencies (up to 40MHz for a 1 Bit wide PWM)
 * 
 * Reference: https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/ledc.html
 * 
 * Key Features:
 * - Support for multiple PWM instances with different configurations
 * - Thread-safe operations
 * - Hardware fade support
 * - Phase shifting for EMI reduction
 * - Hardware fading leveraging the ledc_set_fade_and_start 
 * - Per-channel fade queues with FIFO and CYCLIC modes
 * - Automatic splitting of long fades to work around the LEDC step_num ≤ 1023
 * - Per-reload timing compensation to reduce accumulated latency in queued sequences
 * - Application callbacks for fade completion, queue empty, cyclic wrap, and queue errors
 * - Safe teardown with pending callback tracking to prevent use-after-free
 * Note: All LEDC resources are released in the destructor.
 * 
 *
 *
 ****/

// ---------------------------------------------------------------------------
// SOC-specific calibration table (optional — auto-installed by component.mk)
// ---------------------------------------------------------------------------
#ifdef HWPWM_HAS_SOC_CALIB
// The calibration file lives in src/calibration/ (added to include path by
// component.mk when the file is present) and is generated by TimingTest_HwPWM.
//
// component.mk passes -DHWPWM_SOC_CALIB_HEADER='"HwPwmCalib_<soc>.h"' so we
// can #include it directly without relying on token-pasting (which does not
// work for #include filenames on all preprocessors).
#ifndef HWPWM_SOC_CALIB_HEADER
#error "HWPWM_SOC_CALIB_HEADER must be set by component.mk when HWPWM_HAS_SOC_CALIB is defined"
#endif
#include HWPWM_SOC_CALIB_HEADER
#endif

// ---------------------------------------------------------------------------
// Hardware calibration table storage
// ---------------------------------------------------------------------------
static const Esp32HardwarePwm::CalibrationEntry* s_calibTable = nullptr;
static size_t s_calibCount = 0;

void Esp32HardwarePwm::setCalibrationTable(const CalibrationEntry* table, size_t count)
{
	s_calibTable = table;
	s_calibCount = count;
}

#ifdef HWPWM_HAS_SOC_CALIB
// Auto-register the SOC calibration table at program startup via a static
// initialiser so application code needs no changes between RAW and calibrated runs.
namespace
{
struct HwPwmCalibAutoInstall {
	HwPwmCalibAutoInstall()
	{
		Esp32HardwarePwm::setCalibrationTable(HWPWM_CALIB_TABLE, HWPWM_CALIB_COUNT);
	}
} s_hwPwmCalibAutoInstall;
} // namespace
#endif

namespace
{
/**
 * @brief Compute per-reload overhead correction for a given PWM frequency.
 *
 * Empirically the ISR→task dispatch latency scales approximately proportionally
 * with the LEDC timer period rather than being a fixed constant.  Measurements
 * at 1–2 kHz yield actual_overhead ≈ 3 × period, which fits the model that the
 * overhead is dominated by the time the FreeRTOS main task spends waiting for
 * the next LEDC timer edge after System.queueCallback fires (on average 0.5
 * periods) plus task wake-up latency (also a few periods at low clock rates).
 *
 * At higher frequencies (> 4 kHz) the per-step overhead is small relative to
 * the fade step duration, so under-correction is acceptable.
 *
 * Override per channel via setReloadOverheadUs() to calibrate for your
 * specific hardware using the TimingTest_HwPWM sample.
 */
static uint32_t computeReloadOverhead(uint32_t frequency, ledc_timer_bit_t resolution)
{
	if(frequency == 0) {
		return 0;
	}
	// Check hardware-measured calibration table first.
	for(size_t i = 0; i < s_calibCount; ++i) {
		if(s_calibTable[i].frequency == frequency && s_calibTable[i].resolution == resolution) {
			return s_calibTable[i].overheadUs;
		}
	}
	// Formula fallback: fixed dispatch latency + 1 × timer period.
	//
	// After a fade-done ISR the OS task queue dispatches the callback
	// (typically 1300–1700 µs on ESP32 at 240 MHz) and then LEDC waits
	// for the next timer edge before the new fade starts.  Together:
	//   overhead ≈ DISPATCH_LATENCY_US + 1 × period
	//
	// Empirically calibrated from TimingTest_HwPWM.  Install a full
	// calibration table with setCalibrationTable() for tighter accuracy.
	static constexpr uint32_t DISPATCH_LATENCY_US = 1500;
	return DISPATCH_LATENCY_US + (1000000UL / frequency);
}

/**
 * @brief Calculate maximum duty value for given resolution
 */
uint32_t maxDutyForResolution(ledc_timer_bit_t resolution)
{
	return (1U << resolution) - 1;
}

/**
 * @brief Convert frequency to period in microseconds
 */
uint32_t frequencyToPeriod(uint32_t frequency)
{
	return (frequency == 0) ? 0 : (1000000 / frequency);
}

/**
 * @brief Convert period in microseconds to frequency
 */
uint32_t periodToFrequency(uint32_t period_us)
{
	return (period_us == 0) ? 0 : (1000000 / period_us);
}

} // anonymous namespace

// ---------------------------------------------------------------------------
// Steady (zero-range) fade timer callback
// ---------------------------------------------------------------------------

void Esp32HardwarePwm::steadyFadeTimerCb(void* arg)
{
	auto* ctx = static_cast<SteadyFadeContext*>(arg);
	auto* self = ctx->self;
	uint8_t channel_idx = ctx->channel_idx;
	self->pendingFadeCallbacks_.fetch_or(1u << channel_idx, std::memory_order_relaxed);
	if(!self->fadeCallbackQueued_) {
		self->fadeCallbackQueued_ = true;
		System.queueCallback(Esp32HardwarePwm::dispatchFadeCallbacks, reinterpret_cast<uint32_t>(self));
	}
}

//=============================================================================
// Esp32HardwarePwm Implementation
//=============================================================================

// ---------------------------------------------------------------------------
// Constructors / destructor
// ---------------------------------------------------------------------------

Esp32HardwarePwm::Esp32HardwarePwm(std::vector<uint8_t>& pins, const Config& config)
	: timer_(config.timer), spreadSpectrum_(config.spreadSpectrum), phaseShift_(config.phaseShift)
{
	pins_.resize(pins.size());
	fadeQueues_.resize(pins.size());
	for(auto& q : fadeQueues_) {
		q.entries.resize(FADE_QUEUE_DEPTH);
	}
	steadyFadeCtx_.resize(pins.size());
	for(uint8_t i = 0; i < pins.size(); ++i) {
		steadyFadeCtx_[i] = {this, i};
	}
	steadyFadeTimers_.resize(pins.size());
	for(auto& t : steadyFadeTimers_) {
		t = std::make_unique<SimpleTimer>();
	}

	// basic sanity checks
	if(pins.size() == 0) {
		debug_e("Pin count must be positive");
		return;
	}
	if(pins.size() >= SOC_LEDC_CHANNEL_NUM) {
		debug_e("Pin count exceeds available LEDC channels");
		return;
	}
	if(pins.size() + config.channelStart > SOC_LEDC_CHANNEL_NUM) {
		debug_e("Channel range exceeds available channels");
		return;
	}

	/* ---------------------------------------------------------------
	*   populate the pins_ array
    *   gpioPin is assigned the pin passed in the pins array
    *   channel is counted up from config.channelStart
    *   hpoint is handled according to config.phaseShift.mode:
    *       for AUTO, the hpoint is calculated based on the pin index
    *       for MANUAL, the hpoint is taken from the provided manual_hpoints array
    *           if the number of provided hpoints is less than the number of pins, set the remaining hpoints to 0
    *           if the number of provided hpoints is more than the number of pins, the extra hpoints will be ignored
	* --------------------------------------------------------------- */

	for(uint8_t i = 0; i < pins.size(); ++i) {
		auto& cfg = pins_[i];
		cfg.gpioPin = pins[i];
		cfg.channel = (ledc_channel_t)(config.channelStart + i);

		switch(phaseShift_.mode) {
		case PhaseShiftMode::AUTO:
			cfg.hpoint = calculateHpoint(i);
			break;
		case PhaseShiftMode::MANUAL:
			cfg.hpoint = (i < config.phaseShift.manual_hpoints.size()) ? config.phaseShift.manual_hpoints[i] : 0;
			break;
		case PhaseShiftMode::OFF:
		default:
			cfg.hpoint = 0;
			break;
		}
	}

	// Increment each time the compensation model changes — lets you confirm
	// which firmware build produced a given test output.
	static constexpr uint8_t COMPENSATION_REVISION =
		7; // ..., 6=always split range>1023+cycle_num warning, 7=warn only once+warn only when 0<cycle_num<20
	debug_i("PWM Constructor Configuration [compensation rev %u]:", COMPENSATION_REVISION);
	debug_i("  Timer: num=%d, resolution=%d, freq=%d, speed_mode=%d, clk_cfg=%d", timer_.timer_num, timer_.resolution,
			timer_.frequency, timer_.speed_mode, timer_.clk_cfg);
	debug_i("  SpreadSpectrum: mode=%d, WidthPercent=%d, Subsampling=%d", spreadSpectrum_.mode,
			spreadSpectrum_.WidthPercent, spreadSpectrum_.Subsampling);
	debug_i("  PhaseShiftMode: %d", static_cast<int>(phaseShift_.mode));
	debug_i("  Channel start: %d", config.channelStart);
	debug_i("  Pins : %i", pins.size());
	for(size_t i = 0; i < pins.size(); ++i) {
		debug_i("    Pin[%i]: %d, hpoint: %d", i, pins[i], pins_[i].hpoint);
	}

	initialized_ = initialize();
}

Esp32HardwarePwm::~Esp32HardwarePwm()
{
	if(initialized_) {
		// Stop all channels FIRST — ledc_stop aborts any in-progress hardware fade,
		// preventing the fade-done ISR from firing after this object is destroyed.
		for(const auto& pin : pins_) {
			if(pin.isActive) {
				ledc_stop(timer_.speed_mode, pin.channel, 0);
			}
		}
	}

	if(fadeInstalled_) {
		ledc_fade_func_uninstall();
	}

	if(spreadSpectrumTimer_ != nullptr) {
		esp_timer_stop(spreadSpectrumTimer_);
		esp_timer_delete(spreadSpectrumTimer_);
		spreadSpectrumTimer_ = nullptr;
	}

	if(initialized_) {
		// Pause the timer before deconfiguring — ledc_timer_del rejects a
		// still-running timer with ESP_ERR_INVALID_STATE.
		ledc_timer_pause(timer_.speed_mode, timer_.timer_num);

		ledc_timer_config_t timer_config = {
			.speed_mode = timer_.speed_mode, .timer_num = timer_.timer_num, .deconfigure = true};
		auto result = ledc_timer_config(&timer_config);
	}
}

// ---------------------------------------------------------------------------
// Timer / global configuration
// ---------------------------------------------------------------------------

bool Esp32HardwarePwm::setFrequency(uint32_t frequency)
{
	if(!initialized_ || pins_.empty()) {
		debug_e("setFrequency: not initialized or no pins");
		return false;
	}

	// Update frequency for the timer used by our channels

	esp_err_t result = ledc_set_freq(timer_.speed_mode, timer_.timer_num, frequency);

	if(result != ESP_OK) {
		debug_e("Failed to set frequency: %s", esp_err_to_name(result));
		return false;
	}

	timer_.frequency = frequency;
	// Recompute per-reload overhead correction for the new frequency
	uint32_t overhead = computeReloadOverhead(frequency, timer_.resolution);
	for(auto& q : fadeQueues_) {
		q.reloadOverheadUs = overhead;
	}
	debug_i("Set frequency to %d Hz (reload overhead now %lu µs)", frequency, (unsigned long)overhead);
	return true;
}

uint32_t Esp32HardwarePwm::getFrequency() const
{
	if(!initialized_) {
		return 0;
	}

	return ledc_get_freq(timer_.speed_mode, timer_.timer_num);
}

bool Esp32HardwarePwm::setPeriod(uint32_t period_us)
{
	uint32_t frequency = periodToFrequency(period_us);
	return setFrequency(frequency);
}

uint32_t Esp32HardwarePwm::getPeriod() const
{
	return frequencyToPeriod(getFrequency());
}

uint32_t Esp32HardwarePwm::getMaxDuty() const
{
	return maxDutyForResolution(timer_.resolution);
}

uint8_t Esp32HardwarePwm::getResolution() const
{
	return static_cast<uint8_t>(timer_.resolution);
}

void Esp32HardwarePwm::update()
{
	// todo: this does not do anything meaningful
	if(!initialized_) {
		debug_e("Cannot update: PWM not initialized");
		return;
	}

	// Update all channels
	for(const auto& pin : pins_) {
		if(pin.isActive) {
			ledc_update_duty(timer_.speed_mode, pin.channel);
		}
	}
}

void Esp32HardwarePwm::stopAll(bool idle_level)
{
	for(auto& pin : pins_) {
		ledc_stop(timer_.speed_mode, pin.channel, idle_level);
		pin.isActive = false;
	}
}

// ---------------------------------------------------------------------------
// Primary interface — channel-indexed
// ---------------------------------------------------------------------------

bool Esp32HardwarePwm::setDutyChan(uint8_t channel, uint32_t duty, bool update_immediately)
{
	if(!initialized_ || channel >= pins_.size()) {
		debug_e("setDutyChan: not initialized or channel %d out of range", channel);
		return false;
	}

	auto& cfg = pins_[channel];
	if(cfg.currentDuty == duty) {
		debug_d("Duty for channel %d already at %d, no update needed", channel, duty);
		return true; // no change
	}

	uint32_t max_duty = getMaxDuty();
	if(duty > max_duty) {
		debug_w("Duty %d exceeds maximum %d, clamping", duty, max_duty);
		duty = max_duty;
	}

	debug_i("Setting duty for pin %d channel %d: %d", cfg.gpioPin, cfg.channel, duty);
	cfg.currentDuty = duty;
	ledc_set_duty(timer_.speed_mode, cfg.channel, duty);

	if(update_immediately) {
		debug_i("Updating duty for pin %d channel %d", cfg.gpioPin, cfg.channel);
		ledc_update_duty(timer_.speed_mode, cfg.channel);
	} else {
		debug_i("duty for pin %d channel %d will be updated on next update() call");
	}
	return true;
}

uint32_t Esp32HardwarePwm::getDutyChan(uint8_t channel)
{
	if(!initialized_) {
		return 0;
	}
	if(channel >= pins_.size()) {
		return 0;
	}
	return ledc_get_duty(timer_.speed_mode, pins_[channel].channel);
}

bool Esp32HardwarePwm::setPhaseShiftChan(uint8_t channel, uint32_t phase_shift, bool update_immediately)
{
	if(!initialized_ || channel >= pins_.size()) {
		debug_e("setPhaseShiftChan: not initialized or channel %d out of range", channel);
		return false;
	}

	auto& cfg = pins_[channel];
	cfg.hpoint = phase_shift;

	ledc_set_duty_with_hpoint(timer_.speed_mode, cfg.channel, cfg.currentDuty, cfg.hpoint);
	if(update_immediately) {
		ledc_update_duty(timer_.speed_mode, cfg.channel);
	}
	return true;
}

bool Esp32HardwarePwm::enableFade()
{
	if(fadeInstalled_) {
		return true;
	}

	esp_err_t result = ledc_fade_func_install(0);
	if(result == ESP_OK || result == ESP_ERR_INVALID_STATE) {
		fadeInstalled_ = true;
		return true;
	}
	debug_e("Failed to enable fade: %s", esp_err_to_name(result));
	return false;
}

void Esp32HardwarePwm::disableFade()
{
	if(fadeInstalled_) {
		ledc_fade_func_uninstall(); // disable hardware fade
		fadeInstalled_ = false;
		debug_i("Fade functionality disabled");
	}
}

bool Esp32HardwarePwm::fadeHwChan(uint8_t channel_idx, uint32_t target_duty, uint32_t fade_time_ms)
{
	if(!initialized_ || !fadeInstalled_ || channel_idx >= pins_.size()) {
		debug_e("fadeHwChan: not initialized, fade not installed, or channel %d out of range", channel_idx);
		return false;
	}

	uint32_t max_duty = getMaxDuty();
	if(target_duty > max_duty) {
		target_duty = max_duty;
	}

	fadeDone_[channel_idx] = false;
	pins_[channel_idx].targetDuty = target_duty;
	esp_err_t result = ledc_set_fade_time_and_start(timer_.speed_mode, pins_[channel_idx].channel, target_duty,
													fade_time_ms, LEDC_FADE_NO_WAIT);
	if(result != ESP_OK) {
		fadeDone_[channel_idx] = true;
		debug_e("fadeHwChan failed: %s", esp_err_to_name(result));
		return false;
	}
	return true;
}

bool Esp32HardwarePwm::fadeChan(uint8_t channel_idx, uint32_t target_duty, uint32_t fade_time_ms, bool queue)
{
	if(queue) {
		return queueDutyChan(channel_idx, target_duty, fade_time_ms);
	}
	if(channel_idx >= pins_.size()) {
		return false;
	}
	// Remember whether the channel is mid-fade before we clear the queue.
	// queueDutyChan's auto-start only fires when the channel is idle, so if a
	// fade was running we must force-start the new entry ourselves after enqueue.
	bool wasFading = isFadingChan(channel_idx);
	resetQueue(channel_idx);
	bool ok = queueDutyChan(channel_idx, target_duty, fade_time_ms);
	if(ok && wasFading) {
		startNextFade(channel_idx); // preempts in-progress hw fade on this channel only
	}
	return ok;
}

bool Esp32HardwarePwm::isFadingChan(uint8_t channel_idx) const
{
	if(channel_idx >= pins_.size()) {
		debug_e("isFadingChan: channel %d out of range", channel_idx);
		return false;
	}
	return !fadeDone_[channel_idx];
}

// ---------------------------------------------------------------------------
// Legacy interface — GPIO-pin-indexed
// ---------------------------------------------------------------------------

bool Esp32HardwarePwm::start(uint8_t pin)
{
	if(!initialized_) {
		debug_e("start: not initialized");
		return false;
	}
	return true;
	// todo: do something useful
}

bool Esp32HardwarePwm::stop(uint8_t pin, bool idle_level)
{
	if(!initialized_) {
		debug_e("stop: not initialized");
		return false;
	}

	auto pin_config = getPinConfig(pin);
	if(!pin_config) {
		debug_e("Pin %d not found", pin);
		return false;
	}
	esp_err_t result = ledc_stop(timer_.speed_mode, pin_config->channel, idle_level);

	if(result == ESP_OK) {
		pin_config->isActive = false;
		return true;
	}

	debug_e("stop: ledc_stop failed for pin %d: %s", pin, esp_err_to_name(result));
	return false;
}

void Esp32HardwarePwm::startAll()
{
	// todo: do something useful
}

// ---------------------------------------------------------------------------
// Private
// ---------------------------------------------------------------------------

bool Esp32HardwarePwm::initialize()
{
	debug_i("Esp32HardwarePwm::initialize");

	// Enable LEDC peripheral
	periph_module_enable(PERIPH_LEDC_MODULE);

	if(!enableFade()) {
		debug_e("initialize: enableFade failed");
		return false;
	}

	debug_i("initialize timer");
	// initialize the timer
	ledc_timer_config_t timer_config = {.speed_mode = timer_.speed_mode,
										.duty_resolution = timer_.resolution,
										.timer_num = timer_.timer_num,
										.freq_hz = timer_.frequency,
										.clk_cfg = timer_.clk_cfg};

	auto result = ledc_timer_config(&timer_config);
	if(result != ESP_OK) {
		debug_e("Failed to configure timer: %s", esp_err_to_name(result));
		return false;
	}

	// Allocate channels from resource manager
	debug_i("Esp32HardwarePwm::initialize - getting Channels");

	if(spreadSpectrum_.mode != SpreadSpectrumMode::OFF) {
		// Configure spread spectrum
		debug_i("Configuring spread spectrum");
		setupSpreadSpectrum(timer_.frequency, spreadSpectrum_);
	}

	// Configure each channel
	for(size_t i = 0; i < pins_.size(); ++i) {
		auto& cfg = pins_[i];
		ledc_channel_config_t channel_config = {.gpio_num = cfg.gpioPin,
												.speed_mode = timer_.speed_mode,
												.channel = cfg.channel,
												.intr_type = LEDC_INTR_DISABLE,
												.timer_sel = timer_.timer_num,
												.duty = 0,
												.hpoint = cfg.hpoint};
		debug_i("Channel config: gpio_num=%d, speed_mode=%d, channel=%d, timer_sel=%d, duty=%d, hpoint=%d",
				channel_config.gpio_num, channel_config.speed_mode, channel_config.channel, channel_config.timer_sel,
				channel_config.duty, channel_config.hpoint);

		auto result = ledc_channel_config(&channel_config);
		if(result != ESP_OK) {
			debug_e("Failed to configure pin %d: %s", channel_config.gpio_num, esp_err_to_name(result));
			return false;
		}

		cfg.isActive = true;

		debug_i("configured pin %d:\n  channel: %d\n  hpoint: %d", cfg.gpioPin, cfg.channel, cfg.hpoint);

		ledc_cbs_t cbs = {.fade_cb = &Esp32HardwarePwm::fadeDoneCallback};
		ledc_cb_register(timer_.speed_mode, cfg.channel, &cbs, this);
		fadeDone_[i] = true;
	}

	debug_i("Initialized PWM with %d pins", pins_.size());

	// Auto-compute per-reload correction for all fade queues
	uint32_t overhead = computeReloadOverhead(timer_.frequency, timer_.resolution);
	for(auto& q : fadeQueues_) {
		q.reloadOverheadUs = overhead;
	}
	debug_i("Reload overhead correction: %lu µs/step (1500 µs dispatch + 1 × period=%lu µs)", (unsigned long)overhead,
			(unsigned long)(1000000UL / timer_.frequency));

	return true;
}

bool Esp32HardwarePwm::setupSpreadSpectrum(int frequency, SpreadSpectrumConfig& config)
{
	spreadSpectrum_ = config;
	int interval_us = 1000000 * spreadSpectrum_.Subsampling / frequency;
	esp_timer_create_args_t timer_args = {.callback = &Esp32HardwarePwm::spreadSpectrumTimerCb,
										  .arg = this,
										  .dispatch_method = ESP_TIMER_TASK,
										  .name = "SpreadSpectrum"};
	esp_timer_handle_t timer_handle = nullptr;
	esp_err_t result = esp_timer_create(&timer_args, &timer_handle);
	if(result != ESP_OK) {
		debug_e("Failed to create timer: %s", esp_err_to_name(result));
		return false;
	}
	esp_timer_start_periodic(timer_handle, interval_us);

	if(!timer_handle) {
		debug_e("Failed to create timer");
		return false;
	}

	spreadSpectrumTimer_ = timer_handle;
	return true;
}

bool IRAM_ATTR Esp32HardwarePwm::fadeDoneCallback(const ledc_cb_param_t* param, void* arg)
{
	auto* self = static_cast<Esp32HardwarePwm*>(arg);
	size_t i = param->channel - self->pins_[0].channel;
	if(i < self->pins_.size()) {
		self->pins_[i].currentDuty = self->pins_[i].targetDuty;
		self->fadeDone_[i] = true;
		self->pendingFadeCallbacks_.fetch_or(1u << i, std::memory_order_relaxed);
		if(!self->fadeCallbackQueued_) {
			self->fadeCallbackQueued_ = true;
			System.queueCallback(dispatchFadeCallbacks, reinterpret_cast<uint32_t>(self));
		}
	}
	return false;
}

void Esp32HardwarePwm::spreadSpectrumTimerCb(void* arg)
{
	static_cast<Esp32HardwarePwm*>(arg)->handleSpreadSpectrum();
}

void Esp32HardwarePwm::handleSpreadSpectrum()
{
	int width = (spreadSpectrum_.WidthPercent * timer_.frequency) / 100;
	int r = esp_random() % (2 * width + 1) - width; // r in [-width, +width]
	ledc_set_freq(timer_.speed_mode, timer_.timer_num, timer_.frequency + r);
}

/* ---------------------------------------------------------------------------
* Fade queue handling
* 
* implemented a per-channel fade queue system to allow sequencing multiple fades 
* with different target values and durations without waiting for each fade to 
* complete before issueing the next one. This is useful for creating complex 
* fade patterns or responding to dynamic changes in desired brightness.
*
* during this work, it became obvious that the timing of led_c fade is not
* precise for all combinations of PWM frequency, bit resolution and fade time.
* also, there latency encured between one fade finishing, the led_c fade-done isr firing
* the Sming event dispatch triggering the callback to enqueue the next fade.
* this library tries to provide compensation for those timing issues by
* - splitting long fades into multiple shorter segments that fit within the 
*   reliable timing range, and automatically chaining them together in the queue 
* - providing approximate compensation for the re-queue latency as measured on 
*   specific hardware. Those compensation values can be calculated for other hardware
*   using the TimingTest_HwPWM sample application and set via setReloadOverheadUs()
* ---------------------------------------------------------------------------
*/

static_assert(SOC_LEDC_CHANNEL_NUM <= 32, "pendingFadeCallbacks_ bitmask too narrow for this SoC");

void Esp32HardwarePwm::dispatchFadeCallbacks(uint32_t param)
{
	auto* self = reinterpret_cast<Esp32HardwarePwm*>(param);
	self->fadeCallbackQueued_ = false;

	// Atomically snapshot-and-clear: any ISR firing between the load and the
	// clear would be lost with two separate operations.
	uint32_t pending = self->pendingFadeCallbacks_.exchange(0, std::memory_order_acq_rel);

	for(uint8_t i = 0; i < self->pins_.size(); ++i) {
		if(!(pending & (1u << i))) {
			continue;
		}

		// If an intermediate split-fade segment just finished, start the next one
		// (already in the queue) without surfacing any callbacks — the application
		// only sees the overall fade completing when the final segment finishes.
		if(self->fadeQueues_[i].activeIsIntermediate) {
			self->startNextFade(i);
			continue;
		}

		if(self->onFadeDone_) {
			self->onFadeDone_(i);
		}

		bool more = self->startNextFade(i);
		if(!more && self->onQueueEmpty_)
			self->onQueueEmpty_(i);
	}
}

Esp32HardwarePwm::FadeEntry Esp32HardwarePwm::dequeueFifo(ChannelFadeQueue& q)
{
	FadeEntry entry = q.entries[q.head];
	q.head = (q.head + 1) % (uint16_t)q.entries.size();
	--q.count;
	return entry;
}

bool Esp32HardwarePwm::startNextFade(uint8_t channel_idx)
{
	if(channel_idx >= pins_.size()) {
		return false;
	}

	ChannelFadeQueue& q = fadeQueues_[channel_idx];

	// Helper: apply all per-step corrections to entry.fadeTimeMs and return it.
	// Called for both FIFO and CYCLIC paths with the dequeued/peeked entry.
	//
	// Two independent carry accumulators run here:
	//
	// 1. Reload overhead correction (carryUs):
	//    Every fade reload adds a fixed per-step latency (ISR→task dispatch +
	//    LEDC edge-alignment wait ≈ 3 × timer period).  We deduct this from
	//    successive fade durations so the total sequence time converges to the
	//    commanded total.
	//
	// 2. cycle_num truncation correction (quantCarryUs):
	//    LEDC computes cycle_num = floor(freq × t_ms / (1000 × range)).  The
	//    fractional part is lost each step.  We compute the exact undershoot:
	//      t_actual_us = cycle_num × range × 1_000_000 / freq
	//      undershoot  = t_requested_us − t_actual_us   (always ≥ 0)
	//    The undershoot is accumulated; when it totals ≥ one extra cycle worth
	//    of time (step_period_us = range × 1_000_000 / freq) we add exactly
	//    one timer cycle's worth of milliseconds to the next step, keeping the
	//    total duration accurate to ±1 cycle over an arbitrarily long queue.
	//    When range == 0 (no-op fade) quantization is zero, carry is unchanged.
	auto applyCorrections = [&](FadeEntry& entry) {
		const uint32_t freq = timer_.frequency;
		const uint32_t range = (entry.targetDuty >= pins_[channel_idx].targetDuty)
								   ? (entry.targetDuty - pins_[channel_idx].targetDuty)
								   : (pins_[channel_idx].targetDuty - entry.targetDuty);

		// --- 2. Quantization carry ---
		// cycle_num = floor(freq × t_ms / (1000 × range)) is the number of PWM
		// periods LEDC spends on each duty step.  The fractional part is lost:
		//   undershoot = t_ms×1000 − cycle_num×range×1_000_000/freq  (µs, ≥ 0)
		// We accumulate this across steps and, once ≥ one extra LEDC cycle,
		// extend the next step so that the total sequence duration converges.
		//
		// Guard: when cycle_num == 0 the requested time is below the hardware
		// minimum (LEDC would clamp to 1 cycle giving actual > requested).
		// That is not a truncation artefact we can fix with carry, so skip.
		//
		// Additionally, the correction unit is "one extra LEDC cycle" =
		//   extra_cycle_us = range × 1_000_000/freq  µs.
		// When range is large and freq is low this can be hundreds of
		// milliseconds — larger than the fade itself.  Applying carry in that
		// regime produces multi-ms jumps every N cycles (very visible glitches).
		// Only accumulate when the unit is ≤ 5 ms, where corrections are fine-
		// grained enough to be useful and safe.
		static constexpr uint32_t MAX_QUANT_UNIT_US = 5000; // 5 ms
		if(freq > 0 && range > 0) {
			uint64_t cycle_num = (freq * (uint64_t)entry.fadeTimeMs) / (1000ULL * range);
			// One extra LEDC cycle = range × 1_000_000/freq µs.
			uint32_t extra_cycle_us = (uint32_t)(((uint64_t)range * 1000000ULL) / freq);
			if(cycle_num > 0 && extra_cycle_us > 0 && extra_cycle_us <= MAX_QUANT_UNIT_US) {
				uint64_t t_us = (uint64_t)entry.fadeTimeMs * 1000ULL;
				uint64_t t_actual_us = (cycle_num * (uint64_t)range * 1000000ULL) / freq;
				int32_t undershoot = (int32_t)(t_us - t_actual_us); // µs, ≥ 0
				q.quantCarryUs += undershoot;

				while(q.quantCarryUs >= (int32_t)extra_cycle_us) {
					q.quantCarryUs -= (int32_t)extra_cycle_us;
					uint32_t addMs = extra_cycle_us / 1000;
					entry.fadeTimeMs += (addMs > 0) ? addMs : 1;
				}
			}
		}

		// --- 1. Reload overhead correction ---
		if(q.reloadOverheadUs > 0) {
			q.carryUs += (int32_t)q.reloadOverheadUs;
			int32_t deductMs = q.carryUs / 1000;
			q.carryUs %= 1000;
			if(entry.fadeTimeMs > (uint32_t)deductMs + 1) {
				entry.fadeTimeMs -= (uint32_t)deductMs;
			} else {
				entry.fadeTimeMs = 1;
			}
		}
	};

	// Zero-range guard: if target == current duty, LEDC cannot execute a hardware fade.
	// Handle by firing the callback immediately (fadeTimeMs==0) or via a SimpleTimer.
	auto handleZeroRangeFade = [&](FadeEntry& entry) -> bool {
		applyCorrections(entry);
		if(entry.targetDuty != pins_[channel_idx].targetDuty) {
			return false;
		}
		// Mark channel as "fading" so isFadingChan() returns true for the
		// duration of the steady-hold.  Without this a caller can re-enter
		// fadeChan before the timer fires, corrupt the
		// queue, and lose the pending callback.
		fadeDone_[channel_idx] = false;
		q.activeIsIntermediate = entry.isPartial;
		if(entry.fadeTimeMs == 0) {
			pendingFadeCallbacks_.fetch_or(1u << channel_idx, std::memory_order_relaxed);
			if(!fadeCallbackQueued_) {
				fadeCallbackQueued_ = true;
				System.queueCallback(dispatchFadeCallbacks, reinterpret_cast<uint32_t>(this));
			}
		} else {
			steadyFadeTimers_[channel_idx]
				->initializeMs(entry.fadeTimeMs, steadyFadeTimerCb, &steadyFadeCtx_[channel_idx])
				.startOnce();
		}
		return true;
	};

	if(q.mode == QueueMode::FIFO) {
		if(q.count == 0)
			return false;
		FadeEntry entry = dequeueFifo(q);
		q.activeIsIntermediate = entry.isPartial;
		if(handleZeroRangeFade(entry)) {
			return true;
		}
		return fadeHwChan(channel_idx, entry.targetDuty, entry.fadeTimeMs);
	}

	// CYCLIC
	if(q.cycleLen == 0) {
		return false;
	}
	FadeEntry entry = q.entries[q.head];
	q.activeIsIntermediate = entry.isPartial;
	uint16_t nextHead = (q.head + 1) % q.cycleLen;
	if(nextHead == 0 && onCyclicWrap_) {
		onCyclicWrap_(channel_idx);
	}
	q.head = nextHead;
	if(handleZeroRangeFade(entry)) {
		return true;
	}
	return fadeHwChan(channel_idx, entry.targetDuty, entry.fadeTimeMs);
}

void Esp32HardwarePwm::setQueueMode(uint8_t channel, QueueMode mode)
{
	if(channel >= pins_.size()) {
		return;
	}
	fadeQueues_[channel].mode = mode;
	// FIFO auto-starts on first entry; CYCLIC waits for an explicit startQueue() call
	fadeQueues_[channel].autoStart = (mode == QueueMode::FIFO);
}

Esp32HardwarePwm::QueueMode Esp32HardwarePwm::getQueueMode(uint8_t channel) const
{
	if(channel >= pins_.size()) {
		return QueueMode::FIFO;
	}
	return fadeQueues_[channel].mode;
}

uint16_t Esp32HardwarePwm::getQueueEntries(uint8_t channel) const
{
	if(channel >= pins_.size()) {
		return 0;
	}
	const ChannelFadeQueue& q = fadeQueues_[channel];
	return (q.mode == QueueMode::FIFO) ? q.count : q.cycleLen;
}

void Esp32HardwarePwm::resetQueue(uint8_t channel)
{
	if(channel >= pins_.size()) {
		return;
	}
	auto& q = fadeQueues_[channel];
	size_t cap = q.entries.size();
	uint32_t overhead = q.reloadOverheadUs; // preserve auto-computed correction
	q = ChannelFadeQueue{};
	q.entries.resize(cap);
	q.reloadOverheadUs = overhead;
}

bool Esp32HardwarePwm::startQueue(uint8_t channel)
{
	if(!initialized_ || !fadeInstalled_ || channel >= pins_.size()) {
		return false;
	}
	if(isFadingChan(channel)) {
		return false;
	}
	const ChannelFadeQueue& q = fadeQueues_[channel];
	if(q.mode == QueueMode::FIFO && q.count == 0) {
		return false;
	}
	if(q.mode == QueueMode::CYCLIC && q.cycleLen == 0) {
		return false;
	}
	return startNextFade(channel);
}

bool Esp32HardwarePwm::setQueueCapacity(uint8_t channel, uint16_t depth)
{
	if(channel >= pins_.size() || depth == 0) {
		return false;
	}
	ChannelFadeQueue& q = fadeQueues_[channel];
	if(q.count > 0 || q.cycleLen > 0) {
		return false; // queue not empty, refuse resize
	}
	q.entries.resize(depth);
	return true;
}

uint16_t Esp32HardwarePwm::getQueueCapacity(uint8_t channel) const
{
	if(channel >= pins_.size()) {
		return 0;
	}
	return (uint16_t)fadeQueues_[channel].entries.size();
}

void Esp32HardwarePwm::setQueueAutoStart(uint8_t channel, bool autoStart)
{
	if(channel >= pins_.size()) {
		return;
	}
	fadeQueues_[channel].autoStart = autoStart;
}

bool Esp32HardwarePwm::getQueueAutoStart(uint8_t channel) const
{
	if(channel >= pins_.size()) {
		return true;
	}
	return fadeQueues_[channel].autoStart;
}

void Esp32HardwarePwm::setReloadOverheadUs(uint8_t channel, uint32_t overheadUs)
{
	if(channel >= pins_.size()) {
		return;
	}
	fadeQueues_[channel].reloadOverheadUs = overheadUs;
	fadeQueues_[channel].carryUs = 0; // reset carry when overhead changes
}

uint32_t Esp32HardwarePwm::getReloadOverheadUs(uint8_t channel) const
{
	if(channel >= pins_.size()) {
		return 0;
	}
	return fadeQueues_[channel].reloadOverheadUs;
}

bool Esp32HardwarePwm::queueDutyChan(uint8_t channel, uint32_t targetDuty, uint32_t fadeTimeMs)
{
	if(!initialized_ || !fadeInstalled_ || channel >= pins_.size()) {
		debug_e("queueDutyChan: not initialized, fade not installed, or channel %d out of range", channel);
		return false;
	}

	ChannelFadeQueue& q = fadeQueues_[channel];
	uint16_t currentCount = (q.mode == QueueMode::FIFO) ? q.count : q.cycleLen;

	if(targetDuty > getMaxDuty()) {
		targetDuty = getMaxDuty();
	}

	// Determine the duty level this entry will start from: the target of the
	// last queued entry, or the channel's current target if the queue is empty.
	uint32_t fromDuty = (currentCount > 0)
							? q.entries[(q.tail == 0 ? (uint16_t)q.entries.size() : q.tail) - 1].targetDuty
							: pins_[channel].targetDuty;

	uint32_t rangeAbs = (targetDuty >= fromDuty) ? (targetDuty - fromDuty) : (fromDuty - targetDuty);

	// -----------------------------------------------------------------------
	// Splitting: why it exists, what it fixes and what it cannot fix
	//
	// The LEDC hardware has a 10-bit step_num field (max 1023).  When the duty
	// range of a fade exceeds 1023 counts, the driver sets scale = ceil(range/1023),
	// meaning the duty advances by `scale` counts per timer cycle instead of 1.
	// Result: up to (scale-1)/scale of all intermediate duty values are skipped.
	// At 12-bit (range=4095), scale=4 — only one in four values is visited.
	// Splitting the fade into ≤1023-step segments keeps scale=1 throughout, so
	// every duty value is reached.  This is purely a WAVEFORM SMOOTHNESS fix.
	//
	// Splitting does NOT fix timing accuracy.  The hardware computes:
	//
	//   cycle_num = floor(freq × fadeTimeMs / (1000 × range))
	//
	// The fractional part is truncated — the fade always ends slightly early.
	// Since t/range is the same for every segment, cycle_num is INVARIANT under
	// proportional splitting (N cancels), so timing error is identical whether
	// the fade is split or not.  Split anyway for waveform quality.
	//
	// The one exception: if cycle_num == 0 (requested duration is shorter than
	// one LEDC timer cycle), LEDC clamps to 1 cycle — the fade runs LONGER than
	// requested.  Each split segment would also have cycle_num == 0 and be
	// clamped individually, making the total much longer.  Refuse to split in
	// that case.
	// -----------------------------------------------------------------------

	// Compute cycle_num for this fade (same value for any proportional sub-segment).
	uint64_t cycle_num = (rangeAbs > 0) ? ((uint64_t)timer_.frequency * fadeTimeMs) / (1000ULL * rangeAbs) : 0;

	// Warn when cycle_num is in the timing-error regime (1 ≤ cycle_num < SPLIT_STEP_QUALITY).
	// In this range the LEDC integer truncation error is large (cycle_num=4 → ~20% short).
	//
	// cycle_num == 0 means scale > 1 (LEDC advances duty by multiple counts per period).
	// Timing is approximately correct in that regime — no warning needed.
	//
	// Only warn once per channel/session to avoid UART latency affecting timing.
	static constexpr uint32_t SPLIT_STEP_QUALITY = 20;
	if(rangeAbs > 0 && cycle_num > 0 && cycle_num < SPLIT_STEP_QUALITY && !q.warnedLowCycleNum) {
		q.warnedLowCycleNum = true;
		uint64_t t_actual_us = (cycle_num * (uint64_t)rangeAbs * 1000000ULL) / timer_.frequency;
		// Minimum frequency needed to reach cycle_num == SPLIT_STEP_QUALITY for this fade:
		//   freq_min = SPLIT_STEP_QUALITY * 1000 * rangeAbs / fadeTimeMs
		uint32_t freq_min = (uint32_t)(((uint64_t)SPLIT_STEP_QUALITY * 1000ULL * rangeAbs) / fadeTimeMs);
		debug_w("queueDutyChan: ch%d cycle_num=%llu (< %lu) — fade may be %lld ms short (hw limit). "
				"Fix: increase fadeTimeMs, lower resolution, or raise frequency to >= %lu Hz",
				channel, (unsigned long long)cycle_num, (unsigned long)SPLIT_STEP_QUALITY,
				(long long)((int64_t)fadeTimeMs - (int64_t)(t_actual_us / 1000)), (unsigned long)freq_min);
	}

	// Split when range > 1023 (scale > 1) AND cycle_num >= 1 (not below hw minimum).
	bool shouldSplit = (rangeAbs > 1023) && (cycle_num >= 1);
	uint16_t nSegs = shouldSplit ? (uint16_t)((rangeAbs + 1022) / 1023) : 1;

	// If the split segments don't all fit, degrade gracefully to a single unsplit
	// entry rather than silently failing.  The hardware will use scale≥2 with some
	// timing error, but the fade will still execute.
	if(nSegs > 1 && currentCount + nSegs > (uint16_t)q.entries.size()) {
		if(currentCount + 1 <= (uint16_t)q.entries.size()) {
			debug_w("queueDutyChan: ch%d split (%d segs) won't fit, falling back to unsplit", channel, nSegs);
			if(onQueueError_) {
				onQueueError_(channel, QueueError::SPLIT_DEGRADED);
			}
			nSegs = 1;
		} else {
			debug_d("queueDutyChan: channel %d queue full (%d entries, need %d slots)", channel, currentCount, nSegs);
			if(onQueueError_) {
				onQueueError_(channel, QueueError::QUEUE_FULL);
			}
			return false;
		}
	} else if(nSegs == 1 && currentCount + 1 > (uint16_t)q.entries.size()) {
		debug_d("queueDutyChan: channel %d queue full", channel);
		if(onQueueError_) {
			onQueueError_(channel, QueueError::QUEUE_FULL);
		}
		return false;
	}

	int64_t totalRange = (int64_t)targetDuty - (int64_t)fromDuty;
	for(uint16_t s = 0; s < nSegs; ++s) {
		uint32_t segEnd = (uint32_t)((int64_t)fromDuty + totalRange * (s + 1) / nSegs);
		uint32_t segStart = (uint32_t)((int64_t)fromDuty + totalRange * s / nSegs);
		uint32_t segRange = (segEnd >= segStart) ? (segEnd - segStart) : (segStart - segEnd);
		uint32_t segTimeMs = (rangeAbs > 0) ? (uint32_t)((uint64_t)fadeTimeMs * segRange / rangeAbs) : 1;
		if(segTimeMs == 0) {
			segTimeMs = 1;
		}
		q.entries[q.tail] = {segEnd, segTimeMs, /*isPartial=*/(s < nSegs - 1)};
		q.tail = (q.tail + 1) % (uint16_t)q.entries.size();
	}

	if(q.mode == QueueMode::FIFO) {
		q.count += nSegs;
	} else {
		q.cycleLen += nSegs;
	}

	// Auto-start: only when the first logical entry is being added and channel is idle
	if(q.autoStart && !isFadingChan(channel) && currentCount == 0) {
		startNextFade(channel);
	}

	return true;
}
